# 端口
server:
  port: 80

# datasource, 自己建一个application-db.yml配置文件
spring:
  profiles:
    active: db
    # 时间转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #    上传文件大小限制
  servlet:
    multipart:
      max-file-size: 5MB


# 分页 方言
pagehelper:
  helper-dialect: mysql

# log
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug



