# 端口
server:
  port: 80

# datasource, 自己建一个application-db.yml配置文件
spring:
  profiles:
    active: db, aliyun
    # 时间转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #    上传文件大小限制
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    druid:
      filters: stat

# 分页 方言
pagehelper:
  helper-dialect: mysql

# log
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug

mybatis:
  type-handlers-package: com.cskaoyan.mall.util

#oss
mall:
  aliyun:
    oss:
      access-key-id: LTAI4FnveVphaSkUmcAipBQn
      bucket: cspat
      end-point: oss-cn-shenzhen.aliyuncs.com
      access-secret: 75HtjwSFG6xpD5rLjHs8uipLIdaKOq