# 端口
server:
  port: 80

# datasource, 自己建一个application-db.yml配置文件
spring:
  profiles:
    active: db

# 分页 方言
pagehelper:
  helper-dialect: mysql

# log
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
